services:
  frontend:
    image: node:latest
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - '1413:3000'
    depends_on:
      - backend
      - keycloak
    networks:
      - phishiq-network

  backend:
    image: node:latest
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - '1421:3000'
    depends_on:
      - keycloak
      - postgres
    networks:
      - phishiq-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - phishiq-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - phishiq-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - phishiq-network

networks:
  phishiq-network:
    driver: bridge

volumes:
  postgres-data:
