services:
  frontend:
    container_name: phishiq-frontend
    image: node:latest
    restart: unless-stopped
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "1413:1413"
    depends_on:
      - backend
    networks:
      - phishiq-network
    stdin_open: true
    tty: true

  backend:
    container_name: phishiq-backend
    image: node:latest
    restart: unless-stopped
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - "1421:1421"
    networks:
      - phishiq-network
    stdin_open: true
    tty: true
  
  postgres:
    image: postgres:16
    container_name: postgres16-phishiq
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - phishiq-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-phishiq
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - phishiq-network

networks:
  phishiq-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local