services:
  frontend:
    container_name: phishiq-frontend
    image: node:latest
    restart: unless-stopped
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "1413:1413"
    depends_on:
      - backend
    networks:
      - phishiq-network
    stdin_open: true
    tty: true

  backend:
    container_name: phishiq-backend
    image: node:latest
    restart: unless-stopped
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - "1421:1421"
    networks:
      - phishiq-network
    stdin_open: true
    tty: true

networks:
  phishiq-network:
    driver: bridge
