export enum TipoLog {
  LOGIN = 'LOGIN',
  CRIACAO = 'CRIACAO',
  ATUALIZACAO = 'ATUALIZACAO',
  DELECAO = 'DELECAO',
  TESTE_ENVIADO = 'TESTE_ENVIADO',
  TESTE_CLICADO = 'TESTE_CLICADO',
  OUTRO = 'OUTRO',
}
